<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\App_DAL\App_DAL.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Dtos\" />
      <Folder Include="Mapper\" />
      <Folder Include="Services\Abstraction\" />
      <Folder Include="Services\Implementation\" />
    </ItemGroup>

</Project>
